### ISSUE TITLE
404 crashes with a simple express app

### ISSUE THREAD

**Issue by slooker** [FormidableLabs/express-winston-middleware#9]
I ran into an error when I accidentally typo-ed a URL.  

The error is like so:

    /Users/slooker/code/winston-test/node_modules/express-winston-middleware/index.js:263
          return this._log[level].apply(this._log, args);
                                 ^
    TypeError: Cannot read property 'apply' of undefined
        at self.(anonymous function) [as warning] (/Users/slooker/code/winston-test/node_modules/express-winston-middleware/index.js:263:30)
        at ServerResponse.res.end (/Users/slooker/code/winston-test/node_modules/express-winston-middleware/index.js:103:31)
        at Array.write (/Users/slooker/code/winston-test/node_modules/express/node_modules/finalhandler/index.js:137:9)
        at listener (/Users/slooker/code/winston-test/node_modules/express/node_modules/on-finished/index.js:169:15)
        at onFinish (/Users/slooker/code/winston-test/node_modules/express/node_modules/on-finished/index.js:100:5)
        at callback (/Users/slooker/code/winston-test/node_modules/express/node_modules/on-finished/node_modules/ee-first/index.js:55:10)
        at IncomingMessage.onevent (/Users/slooker/code/winston-test/node_modules/express/node_modules/on-finished/node_modules/ee-first/index.js:93:5)
        at IncomingMessage.emit (events.js:104:17)
        at _stream_readable.js:908:16
        at process._tickCallback (node.js:355:11)

I have a super simple demo that I put up on github that you can clone and see the demo if you hit any url OTHER than /

https://github.com/slooker/express-winston-middleware-error

**Comment by slooker** [comment]
This happens even if I add the error handing from express-winston-middleware like so:

    app.use(winMid.error({
      transports: [ new (winston.transports.Console)({ json: true }) ]
    }));

**Comment by ryan-roemer** [comment]
@slooker -- Confirmed. I'll have a fix out soon.

**Comment by slooker** [comment]
Cheers!

**Comment by ryan-roemer** [comment]
Fix released in `v0.0.6`. Let me know if anything doesn't work. Thanks!

**Comment by slooker** [comment]
Work great!  Thanks for the quick turn around!
